#ifndef __SEISMOMETER_CONFIG_HPP__
#define __SEISMOMETER_CONFIG_HPP__

/* Primary data sample rate in Hz */
#define SEISOMETER_SAMPLE_RATE        100
#define SEISOMETER_SAMPLE_PERIOD_US   ((1000*1000)/SEISOMETER_SAMPLE_RATE)
#define SEISOMETER_WATCHDOG_PERIOD_US (3*SEISOMETER_SAMPLE_PERIOD_US)

#endif /*__SEISMOMETER_CONFIG_HPP__*/