#ifndef __SEISMOMETER_CONFIG_HPP__
#define __SEISMOMETER_CONFIG_HPP__

/* Primary data sample rate in Hz */
#define SEISMOMETER_SAMPLE_RATE        100
#define SEISMOMETER_SAMPLE_PERIOD_US   ((1000*1000)/SEISMOMETER_SAMPLE_RATE)
#define SEISMOMETER_WATCHDOG_PERIOD_MS 250
//#define SEISMOMETER_WATCHDOG_PERIOD_MS 8000

#define SEISMOMETER_SAMPLE_QUEUE_SIZE 1024

//#define SEISMOMETER_SAMPLE_DEBUG_PRINT

#endif /*__SEISMOMETER_CONFIG_HPP__*/